### ISSUE TITLE
Nombres

### ISSUE THREAD

**Issue by matipan** [Agusss19/node#1]
En cuanto a los nombres de los paquetes. Como estandar todos los paquetes se nombran con lower case, los archivos tambien.
https://github.com/Agusss19/node/blob/c487c0c3a7b8eabe3075f000bf94ef45174721b0/src/Node/Node.go#L6-L11
Pensa lo siguiente, si ya estas referenciando el paquete `TCPServer` como `tcpserver` en tu codigo, porque no nombrarlo asi? Todos los imports se simplificarian. Pasaria a ser:
```go
        ...
	"node/src/command"
	"node/src/keepalive"
	"node/src/multicastsender"
        ...
```
Y todos los archivos tambien, `tcpserver.go` en vez de `TCPServer.go` (no es java esto 😛 )
Ya que estamos en el tema de imports. Algo que siempre se hace es usar "absolute paths" en vez de relative paths. Esto da un panorama un poco mas claro y dentro de poco(cuando salga go 1.11) va a ser obligatorio(dsp hablamos las razones, es de hecho bastante interesante). Entonces ahora los imports serian asi:
```go
        ...
	"github.com/agusss19/node/src/command"
	"github.com/agusss19/node/src/keepalive"
	"github.com/agusss19/node/src/multicastsender"
        ...
```

**Comment by matipan** [comment]
Referencia: https://golang.org/doc/effective_go.html#names

**Comment by matipan** [comment]
Y ahora el tema de la estructura de carpetas. En go no se recomienda tener la carpeta `src`, porque eso siempre lleva a TODO este dentro de esa carpeta, entonces para que? jajaj. Te dejo un repo donde se tiene el tipico layout de un proyecto de go: https://github.com/golang-standards/project-layout
Obviamente que no todas esas carpetas van en todos los proyectos. Uno simplemente tiene que identificar las cosas que van y las que no para su proyecto en particular

**Comment by Agusss19** [comment]
Esto ya está solucionado. Como se procede a partir de ahora?
