### ISSUE TITLE
Formato de new

### ISSUE THREAD

**Issue by matipan** [Agusss19/node#3]
https://github.com/Agusss19/node/blob/d204fc288aa9040dcfe2bd85380bb643f571c973/pkg/qsywifipacket/qsywifipacket.go#L85-L111
Por lo general cuando tenes la estructura New que devuelve un packet, en vez de hacer asignacion linea por linea se suele usar el tipico asignacion grupal:
```go
return &QSYWiFiPacket{
            signature: [3]byte{'Q', 'S', 'Y'},
            packetType: packetType,
            id: id,
            color: color,
            delay: delay,
            step: step,
}, nil
```

**Comment by Agusss19** [comment]
Esto ya está para testear.
